### ISSUE TITLE
Guide to run the Mailgun batch

### ISSUE THREAD

**Issue by DonSalvador** [leondeng/laravel-batch-mailgun#2]
Hello.

Is there any guide to run the Mailgun batch?
Is it compatible with blade or do I have to use Mailgun variables?

Thanks

**Comment by leondeng** [comment]
Hi @DonSalvador , sorry for my late reply.

This package is all compatible to Laravel Mailable mail.
So, you can still use view and data for the email building.

The `batch` logic only happens if the flag MAILGUN_BATCH_SENDING in env set. Where it tweaks the mail payload if there are 1+ recipients.
